spring:
  application:
    name: user-center
    # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yupi
    username: root\
    password: 123456
  # session失效时间：1天=86400s
  session:
    timeout: 20

server:
  port: 8090

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  # 逻辑删除
  # 步骤 1: 配置com.baomidou.mybatisplus.core.config.GlobalConfig$DbConfig
  # 步骤 2: 实体类字段上加上@TableLogic注解
  global-config:
    db-config:
      logic-delete-field: isDeleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)



